apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - democratic-csi
    - external-dns
    - ingress-nginx
    - secrets
    - cilium-config
    - cert-
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/apps
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
