apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:

  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/system/democratic_csi
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
