apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - secrets
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/system/external_dns
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
