apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - cert-manager
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/system/ingress-nginx
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
