apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: bws_operator
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/secrets/
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
