apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
data:
  password: ENC[AES256_GCM,data:mHAxapRcbHnc,iv:LZgScBGq6B4NdCuTb7nitbW/SVjNXPXplShbnJsKub8=,tag:nYemO8zNEu+DaFEj+0OW9w==,type:str]
  user: ENC[AES256_GCM,data:IzGWl+g=,iv:ioE30J1L/L5MJIPvK2DlcKl4EXSRW/QONp9ZgnoF/j4=,tag:z0gdzQ62c5lzMrLy9oxxtQ==,type:str]
sops:
  kms: [ ]
  gcp_kms: [ ]
  azure_kv: [ ]
  hc_vault: [ ]
  age: [ ]
  lastmodified: "2024-12-21T21:58:54Z"
  mac: ENC[AES256_GCM,data:g/XwFSv28Xr9pzgIe17sTUQVerUOA1/0PNRsNEqVnb8c3fW5VznVfAdwkY3p00BlAVNAt4lQnNYGyOeZ5EY3WKp9qWBEgU2te/ci/6wab8XXqQSIbMMqraa1UjROYxpwilKofNIrncFN4qfoHxnkbsdxQ8Gmw6nbWgyWEKtRg7M=,iv:8lrWhrRXytx2Ke1ane9vuFAmXXC/YcDfEx2LN3v/n/4=,tag:K2GvSbWpem2xeXqA7HQglA==,type:str]
  pgp:
    - created_at: "2024-12-21T21:58:54Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----
        
        hF4DU+GaVkdTfp0SAQdAGPeQlbmtY59EWSrRrK7yKgKOEu9J+hodUry5yaF6alEw
        4j9UpEke1JlQJ6T6RDmf2YE0KCg/7tvz0J1/7mpSixQsxnNuxp8AUTWsXHj942wB
        1GgBCQIQ2kIcr54ZfwlrSLmDkHI6yWVEwQSdc4SeAnbb1hcEHFlOHFXkoplxT0QQ
        rkMj+BNyJETfzoxRQnHEpQKrkzgtvXEVEX4D0VnYudHQxc2DfzdiulyHgcekmehz
        /iPseOR21lBS+w==
        =PGU7
        -----END PGP MESSAGE-----
      fp: 1AB4CEBCE4D3CD6A23AA59104C16B8CD8B6050E3
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
