---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: democratic-csi
    app.kubernetes.io/instance: democratic-csi
    app.kubernetes.io/part-of: democratic-csi
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/created-by: flux
  name: bitwarden-secrets
  namespace: system
spec:
  organizationId: ec777f46-55b2-40d1-986f-b1da0138d5bb
  secretName: bitwarden-secrets
  map:
    - bwSecretId: d9a1b56c-6fad-4f0d-b8fa-b24b018071a7
      secretKeyName: api-token
  authToken:
    secretName: bw-auth-token
    secretKey: token
