apiVersion: v1
kind: Secret
metadata:
  name: sso-secrets
  namespace: linkwarden
stringData:
  NEXT_PUBLIC_AUTHENTIK_ENABLED: ENC[AES256_GCM,data:0B2shg==,iv:8WTkUJu+aDEOa30GI2fQtJDlaHQW905cVhbFAQpDDNU=,tag:dhpCcvUZ4zQtjJLfdFOtRg==,type:str]
  AUTHENTIK_CUSTOM_NAME: ENC[AES256_GCM,data:1HjIm6Bmd9Ru,iv:5cH9Y+47VEnA1AKXZ8HLPoGoMeGL4vNzLkBfc4h6Bbk=,tag:xvso/4z5cjTXVBGwL0qlQQ==,type:str]
  AUTHENTIK_ISSUER: ENC[AES256_GCM,data:wuVWZymxLGPt6wE/og+8+5+Hin1M1Vv30SwpMkjmHf3hFQuf3Yqap9iNvvgN+A==,iv:bwWRGVmkcHQdQZLt6CnDqZwxj50en3ZAgVw68urH7Tw=,tag:Q8ERlpK/fwFX0c3oABX0/Q==,type:str]
  AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:UaLqpqorTY/TPykzGLBTiJiB1+vUYddtw0MT9WUVp6uvTjuspSuUYQ==,iv:iqyrKY0eLeJbKGD1uvh2ff2t69J2WZpPzghr+rU1API=,tag:g2c0HKxjSwvgGnOvBAwPqw==,type:str]
  AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:yaZK/4U4hTs8qmYXvgZvTWoQ2tgJMaLa4kox/xYrAKW9BwARtgJ0GDjfvsoBjeYLQjlE/zoOEZR461u/YG4MP5kIaQ71dJl785xduZXymK8scxRIyALeX3mrKmIbCmpZ3bfBJvXX1viIZCxIJNffljRyzztG5aBOsilp4ghN/zo=,iv:A41jziCJqFiAEn9NUenXtHWmvoJIxmlvBbx9Ku51EjI=,tag:AdEAvtCarLFuKKJpjwU0Aw==,type:str]
sops:
  kms: [ ]
  gcp_kms: [ ]
  azure_kv: [ ]
  hc_vault: [ ]
  age: [ ]
  lastmodified: "2024-12-25T23:22:37Z"
  mac: ENC[AES256_GCM,data:D7X3498+HaUrtQ1gWWRUo7c7OKvvDaoUSWPruEeTCiLsCCe5syD8shfiYRxA241UjLf9SjCrJqSmgAkL80y1yUUK9f/FW8jXcy2D0n0mHeZcEmShXHQbZrbvscTZqSrmohMeTA9DiACChiJezdhNz3zxQYa+hWhYnA0v5eMuZjw=,iv:inPDp9JtB/dTD/E/F54r12ZnbkxKbqL94Ln2Hn5QUkA=,tag:c8ighDrCEC69eTqJ9CzxKQ==,type:str]
  pgp:
    - created_at: "2024-12-25T23:22:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----
        
        hF4DU+GaVkdTfp0SAQdAXGK6zzefXyxo3rc00JCC0MSS0Xfy99DWo//A7Ckfei0w
        Li7VUvHcnwcK5Qhqi7v6NvQrlEZgFLBbKCVcO3vh1Hex2BjMQmJHUQenrkbqA9+w
        1GgBCQIQUE2u4LH0SJjk1yMylPg92hyCFDgDFcuPXfzYdS8IUJGQLIcoCLGkQ9NQ
        hPM/iHfi1LIpZpnGs1riWAvJcJaD2rnWEDWdTKTQxx+WlfnARRwtnMKzhK+S7+G7
        YNTfXU81wHiA7Q==
        =/uoa
        -----END PGP MESSAGE-----
      fp: 1AB4CEBCE4D3CD6A23AA59104C16B8CD8B6050E3
  encrypted_regex: stringData
  version: 3.9.2
