apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-persistent
