apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smtp.k8s.ddole.net
  namespace: stalwart-mail
spec:
  secretName: cert-smtp.k8s.ddole.net
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - "smtp.k8s.ddole.net"
