apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-config
  namespace: stalwart-mail
data:
  config.toml: |
    authentication.fallback-admin.secret = "admin"
    authentication.fallback-admin.user = "admin"
    directory.internal.store = "rocksdb"
    directory.internal.type = "internal"
    lookup.default.hostname = "smtp.k8s.ddole.net"
    server.listener.https.bind = "[::]:443"
    server.listener.https.protocol = "http"
    server.listener.https.tls.implicit = true
    server.listener.smtp.bind = "[::]:25"
    server.listener.smtp.protocol = "smtp"
    server.listener.submission.bind = "[::]:587"
    server.listener.submission.protocol = "smtp"
    server.listener.submissions.bind = "[::]:465"
    server.listener.submissions.protocol = "smtp"
    server.listener.submissions.tls.implicit = true
    storage.blob = "rocksdb"
    storage.data = "rocksdb"
    storage.directory = "internal"
    storage.fts = "rocksdb"
    storage.lookup = "rocksdb"
    store.rocksdb.compression = "lz4"
    store.rocksdb.path = "/opt/stalwart-mail/data"
    store.rocksdb.type = "rocksdb"
    tracer.log.ansi = false
    tracer.log.enable = true
    tracer.log.level = "info"
    tracer.log.path = "/opt/stalwart-mail/logs"
    tracer.log.prefix = "stalwart.log"
    tracer.log.rotate = "daily"
    tracer.log.type = "log"
    [certificate."default"]
    cert = "%{file:/etc/mail-certs/cert.fullchain.pem}%"
    private-key = "%{file:/etc/mail-certs/cert.privkey.pem}%"
    default = true
