apiVersion: v1
kind: Service
metadata:
  name: stalwart-mail
  namespace: stalwart-mail
  labels:
    app.kubernetes.io/name: stalwart-mail
    app.kubernetes.io/version: v0.10.7
    app.kubernetes.io/managed-by: manifest
    access: private
  annotations:
    external-dns.alpha.kubernetes.io/hostname: smtp.k8s.ddole.net
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 443
    - name: smtp
      port: 25
      targetPort: 25
    - name: submission
      port: 587
      targetPort: 587
    - name: smtps
      port: 465
      targetPort: 465
    - name: imap
      port: 143
      targetPort: 143
    - name: imaps
      port: 993
      targetPort: 993
    - name: sieve
      port: 4190
      targetPort: 4190
  selector:
    app.kubernetes.io/name: stalwart-mail
    app.kubernetes.io/version: v0.10.7
    app.kubernetes.io/managed-by: manifest
