apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ddole-net-self-signed-wildcard
  namespace: cert-manager
spec:
  secretName: ddole-net-self-signed-wildcard
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: ddole.net
  dnsNames:
    - "*.ddole.net"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
