---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: admin@ddole.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              name: cert-manager-creds
              key: awsAccessKeyID
            secretAccessKeySecretRef:
              name: cert-manager-creds
              key: awsSecretAccessKey
            hostedZoneID: Z05011532DSAQLHAX1739
            region: us-east-1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    email: admin@ddole.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              name: bitwarden-secrets
              key: awsAccessKeyID

            secretAccessKeySecretRef:
              name: bitwarden-secrets
              key: awsSecretAccessKey
            hostedZoneID: Z05011532DSAQLHAX1739
            region: us-east-1
