---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  chart:
    spec:
      chart: vikunja
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vikunja
      version: 0.4.3
  interval: 1m0s
  values: { }
