---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: private
spec:
  blocks:
    - cidr: "10.0.31.0/24"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: internal
spec:
  blocks:
    - cidr: "10.0.32.0/24"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: public
spec:
  blocks:
    - cidr: "10.0.33.0/24"
