---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: private
spec:
  blocks:
    - start: 10.0.31.10
      stop: 10.0.31.250
  serviceSelector:
    matchLabels:
      access: private
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: internal
spec:
  blocks:
    - cidr: "10.0.32.0/24"
  serviceSelector:
    matchLabels:
      access: internal
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: public
spec:
  blocks:
    - cidr: "10.0.33.0/24"
  serviceSelector:
    matchLabels:
      access: public
