apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seafile
  namespace: flux-system
spec:
  dependsOn:
    - name: storage
    - name: ingress-nginx
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/seafile/
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
