apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: <NAME>
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: <PATH TO FOLDER>
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
