apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
spec:
  volumeSnapshotClassName: democratic-csi-nfs-persistent
  source:
    persistentVolumeClaimName: test-claim-nfs-persistent
