#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: test-claim-nfs-ephemeral
#spec:
#  storageClassName: nfs-ephemeral
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 8Gi
#---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs-persistent
spec:
  storageClassName: nfs-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
