---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 12h0m0s
  url: https://kubernetes-sigs.github.io/external-dns/
