---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: democratic-csi
spec:
  chart:
    spec:
      chart: snapshot-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      version: 0.2.4
  interval: 1m0s
  values:
    controller:
      enabled: true
      rbac:
        enabled: true
      replicaCount: 1
      image:
        repository: registry.k8s.io/sig-storage/snapshot-controller
        pullPolicy: IfNotPresent
      args:
        - "--v=5"
        - "--leader-election=true"
        - "--enable-distributed-snapshotting"
      extraArgs: [ ]
    validatingWebhook:
      enabled: false
      rbac:
        enabled: true
      replicaCount: 1
