---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-private
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1h0m0s
  values:
    commonLabels:
      access: private
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: "kube-prometheus-stack"
      allowSnippetAnnotations: "true"
      extraArgs:
        default-ssl-certificate: "cert-manager/ddole-net-le-staging-wildcard"
      service:
        externalTrafficPolicy: Local
      ingressClassResource:
        name: nginx-private
        enabled: true
        default: true
