---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-private
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1h0m0s
  values:
    commonLabels:
      access: private
    controller:
      allowSnippetAnnotations: "true"
      #      extraArgs:
      #        default-ssl-certificate: default/ddole-net-crt
      service:
        externalTrafficPolicy: Local
      ingressClassResource:
        name: nginx-private
        enabled: true
        default: true
