apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard-ingress
  namespace: default
spec:
  tls: [ ]
  rules:
    - host: kuard.ddole.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuard-service
                port:
                  number: 80
